source 'https://github.com/CocoaPods/Specs.git'

pod 'Parse', '1.7.0'
pod 'ParseFacebookUtils', '1.7.0'
pod 'iOS-Slide-Menu', '1.4.5'
pod 'SVPullToRefresh', '0.4.1'
pod 'SVProgressHUD', '1.1.2'
pod 'GoogleAnalytics-iOS-SDK' , '3.0.7'
pod 'AFNetworking', '~> 2.5'
pod 'UIAlertView+Blocks', '0.8.1'
pod 'UIActionSheet+Blocks', '~> 0.8'